# This Action should run on main branch and verify lint, test, and then publish the version on npm
name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: CI Quixer
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Size
        run: pnpm size

      - name: Lint
        run: pnpm lint
