# This Action should run on main branch and verify lint, test, and then publish the version on npm
name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release Quixer
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.QUIXER_GITHUB_BOT_TOKEN }}
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          registry-url: "https://registry.npmjs.org"

      - name: Configure CI Git User
        run: |
          git config user.name quixerbot
          git config user.email quixerbot@github.com

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Size
        run: yarn size

      - name: Lint
        run: yarn lint

      - name: Publish
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
