# This Action should run on main branch and verify lint, test, and then publish the version on npm
name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release Quixer
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      DATABASE_URL: 'mysql://root:root@localhost:3306/quixer'

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.QUIXER_GITHUB_BOT_TOKEN }}
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Configure CI Git User
        run: |
          git config user.name quixerbot
          git config user.email quixerbot@gmail.com

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Set up Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'quixer'
          mysql root password: 'root'

      - name: Install dependencies
        run: pnpm install

      - name: Run Migration
        run: pnpm migrate

      - name: Build
        run: pnpm build

      - name: Size
        run: pnpm size

      - name: Lint
        run: pnpm lint

      - name: Publish
        run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
